### ISSUE TITLE
Proper login and refresh token

### ISSUE THREAD

**Issue by barocsi** [IonicaBizau/youtube-api#21]
Hello,

I used https://developers.google.com/oauthplayground to generate the appropriate OAUTH 2.0 access keys for various youtube V3 API accesses. It gives me the access and refresh tokens. I saw In your code that it supports refresh_token at 

``` js
authObj.setCredentials({
    access_token: options.access_token || options.token
  , refresh_token: options.refresh_token
});
```

however Im not sure on how to use it properly to regenerate an access token automatically using refresh token besides going to playground and generate one manually, OR as it happens on the testing tool you provided it should create a server with a callback and receive the refreshed access token.

Thanks,
Aron

**Comment by bichotll** [comment]
Regarding the refresh token, I found out that it was not being returned by the API unless you set `approval_prompt:'force',` on the generateAuthUrl method...such as:
```js
opn(oauth.generateAuthUrl({
  access_type: "offline",
  approval_prompt:'force',
  scope: ["...scopes..."]
}))
```
