### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by tejasmanohar** [IonicaBizau/youtube-api#29]
Can I search YouTube via this module?

Like making requests to 'http://gdata.youtube.com/feeds/api/videos?q='+ { search_query } +'&format=5&max-results={ }) + ...

**Comment by adrianfalleiro** [comment]
Yeah, you can search like this:
```
Youtube.search.list({
    "part": "snippet"
  , "q": "<Search Query>"
  , "maxResults": 10
  , "type" : 'video'
  }, function (err, data) {
    console.log(data.items)  
  })
```

**Comment by tejasmanohar** [comment]
Ah, I see. But why use this over the normal `googleapis` module? This relies on it.

**Comment by IonicaBizau** [comment]
@adrianfalleiro :+1:

@tejasmanohar See #4, there is a related discussion. 

> But why use this over the normal `googleapis` module?

Because I created this module with this type of syntax before of the current implementation of `googleapis`. After #19 was merged, this module uses `googleapis`, but the syntax didn't change.
