### ISSUE TITLE
Param "mySubscribers" has been deprecated.

### ISSUE THREAD

**Issue by ivolivares** [IonicaBizau/youtube-api#30]
In [documentation](https://developers.google.com/youtube/v3/docs/channels/list), "mySubscribers" parameter appears as deprecated.

**Comment by IonicaBizau** [comment]
Good point! :+1: 

Hopefully this will work:

```sh
// List your subscribers
Youtube.subscriptions.list({
    "part": "id"
  , "mySubscribers": true
  , "maxResults": 50
}, function (err, data) {
    console.log(err || data);
});
```

**Comment by ivolivares** [comment]
Yes! It Works!

**Comment by IonicaBizau** [comment]
@ivolivares Could you please make a PR this snippet?
