### ISSUE TITLE
How to read an object in the data response?

### ISSUE THREAD

**Issue by Chuug** [IonicaBizau/youtube-api#33]
Hi,

I'm relatively new in javascript (and I started node 2 hours ago) and I don't know how to go in a object who's in a json response gave by this app.

A little illustration when I console.log the data response:
![stats](https://cloud.githubusercontent.com/assets/7072863/8347771/c6934716-1b0a-11e5-990e-403dfc9129f6.PNG)

Statistics is an object and I don't know how to pick a value in so if you know a way to get in, that would be great !

here is the object (data.items):
![stats2](https://cloud.githubusercontent.com/assets/7072863/8347843/a913af72-1b0b-11e5-89c6-e6e792e4625a.PNG)

For example, data.items.kind give me "undefined" and that's my problem.

Thanks for the help !

EDIT: data.items[0].kind was the way

**Comment by IonicaBizau** [comment]
@Chuug Happy to hear you found the answer. :smile:

**Comment by Chuug** [comment]
I always find the issue after posting my questions :stuck_out_tongue_winking_eye: 

Thank you for the module man

**Comment by IonicaBizau** [comment]
> I always find the issue after posting my questions :stuck_out_tongue_winking_eye:

Ha! I would like to be like you then! :smile: I ask on StackOverflow and if I don't get any feedback I start opening issues on GitHub... And maybe then I got a solution. :smile_cat: 

You're welcome!

**Comment by Chuug** [comment]
Hi ! I don't know why but now, I get this message when I use data.items[0].kind. To be honest, I don't know why, I didn't update anything. I can't read the items object anymore
![stats3](https://cloud.githubusercontent.com/assets/7072863/9195986/52a0b414-4027-11e5-80be-d49185859c30.PNG)

**Comment by IonicaBizau** [comment]
@Chuug Do the following:

```js
if (data.items[0] === undefined) {
   console.log(data);
}
```

Make sure you handle the errors correctly. :smile:

**Comment by Chuug** [comment]
oh ok I understand now, it's just one undefined who blow up all the script.

My bad :D thanks man

I really need to get more skill on js

**Comment by IonicaBizau** [comment]
No problem. You'll get better at it, I'm sure :smile:
