### ISSUE TITLE
How to upload video to youtube?

### ISSUE THREAD

**Issue by periyasamy25** [IonicaBizau/youtube-api#35]
I want to upload videos to youtube using nodejs so please tell me how to upload videos to youtube using youtube-api.

**Comment by IonicaBizau** [comment]
@periyasamy25 Hey!

I answered this in #20. See [my comment](https://github.com/IonicaBizau/youtube-api/issues/20#issuecomment-52010830). Hopefully it's still working. :sparkle:

**Comment by periyasamy25** [comment]
when i used this method 
Youtube.authenticate({
    type: "key"
  , key: "your server key"
}); it'll show the following error.
{ [Error: Login Required]
  code: 401,
  errors:
   [ { domain: 'global',
       reason: 'required',
       message: 'Login Required',
       locationType: 'header',
       location: 'Authorization' } ] }

**Comment by periyasamy25** [comment]
how to get keyFile for JWT authentication?

**Comment by IonicaBizau** [comment]
They key authentication is used for read-only requests, from what I know. You probably need OAuth (with upload rights) or JWT. [Here](https://github.com/IonicaBizau/learning-jwt) is a helpful resource for learning JWT. :smile:

**Comment by periyasamy25** [comment]
type: "jwt"
  , email: "77....3vv@developer.gserviceaccount.com"
  , keyFile: "... auth.pem"
  , key: "fb....d50"

what is key in this?

**Comment by IonicaBizau** [comment]
@periyasamy25 You get it in the credentials. Did you read [the steps](https://github.com/IonicaBizau/learning-jwt#creating-a-service-account-using-the-google-developers-console)?

**Comment by periyasamy25** [comment]
Yes I got the key and i have used but i got error.
9052:error:0906D06C:PEM routines:PEM_read_bio:no start line:openssl\crypto\pem\p
em_lib.c:703:Expecting: ANY PRIVATE KEY
Error: SignFinal error

**Comment by IonicaBizau** [comment]
@periyasamy25 Did you select *JSON Key* or *P12*? I just checked it right now.

**Comment by IonicaBizau** [comment]
@periyasamy25 Also, I'm not sure but the *key* could be one of the fingerprints. Didn't test...

**Comment by periyasamy25** [comment]
okay.how to get access token in oauth?

**Comment by IonicaBizau** [comment]
@periyasamy25 If you use JWT, that's handled internally. If you're using OAuth, see #5.

**Comment by IonicaBizau** [comment]
@periyasamy25 I added a full example in #37. Actually I was wrong when I said that you can do it with JWT. Apologies. Hope you will enjoy the new example. :smile:
