### ISSUE TITLE
Question: progress callback for insert()

### ISSUE THREAD

**Issue by shiffman** [IonicaBizau/youtube-api#38]
@IonicaBizau, it doesn't look like the youtube api  [`insert()` method](https://developers.google.com/youtube/v3/docs/videos/insert) provides any callback for monitoring upload progress.  This functionality, however, is demonstrated in the API docs with client-side code [outlined here with a `MediaUploader` object](https://developers.google.com/youtube/v3/code_samples/javascript).

There are also some nice ways of doing this with the [python API](https://developers.google.com/youtube/v3/guides/uploading_a_video). 

Am I missing something?  There appears to be only be a "completed" callback for `insert()`?

**Comment by shiffman** [comment]
Interestingly, youtube itself sits on 0% until it is finished.  So progress isn't even shown there?

<img width="395" alt="screen shot 2015-07-10 at 12 06 38 pm" src="https://cloud.githubusercontent.com/assets/191758/8617486/386463c8-26fc-11e5-9c3a-14aaf2b419c7.png">

**Comment by IonicaBizau** [comment]
> Interestingly, youtube itself sits on 0% until it is finished. So progress isn't even shown there?

That's weird, I also noticed it. It's just about video processing I guess, but I am not sure. Maybe for *big* videos it shows the upload progress.

> Am I missing something? There appears to be only be a "completed" callback for insert()?

Since you have the stream, you can do anything with it. For example @freeall created [a module](https://github.com/freeall/progress-stream) to show you the progress. The callback function is fired when the upload is complete (as you noticed).

**Comment by shiffman** [comment]
Oh, that's great, I'm going to try running some tests.   Isn't the stream I have, however, the one reading the video file from the hard drive (`Fs.createReadStream('test.mov')`) rather than the stream sending the data to youtube itself?

**Comment by IonicaBizau** [comment]
It is, but [that's piped in the request](https://github.com/google/google-api-nodejs-client/blob/37904cc8b5c8e223644b7f44195cf866fa84e4dc/lib/apirequest.js#L174-L176). The request object is returned.

If this method doesn't work, try to do access the request object directly:

```js
var ytReq = YouTube.videos.insert(...)
setInterval(function () {
  console.log(ytReq.req.req.connection._bytesDispatched);
}, 250);
```

**Comment by shiffman** [comment]
Brilliant, it's all starting to make sense now.
