### ISSUE TITLE
jwt auth for playlistitem insert

### ISSUE THREAD

**Issue by bradoyler** [IonicaBizau/youtube-api#39]
Hey @IonicaBizau 
I'm attempting to add items to a playlist like so:

```js
var Youtube = require('youtube-api');

var playlistId = 'PLUG0dgd8xRox0HUkTkB1GRuUQ8UF4bKw9';
var videoId = 'rgAwVlR0s5w';

var options = {
    "part"  : "snippet",
    "resource" : {
        "snippet" : {
            "playlistId" : playlistId,
            "resourceId" : {
                "kind" : "youtube#video",
                "videoId" : videoId
            }
        }
    }
};

Youtube.authenticate({
    type: "jwt",
    email: "4476xx@developer.gserviceaccount.com",
    key: "-----BEGIN PRIVATE KEY-----\nMIxxxx\n-----END PRIVATE KEY-----\n",
    scopes: ["https://www.googleapis.com/auth/youtube"]
}).authorize(function (err, data) {
    if (err) {
        return console.error(err);
    }

    Youtube.playlistItems.insert(options, function(err, resp){
        if(err) {
            console.log(JSON.stringify(err));
        }
        console.log(JSON.stringify(resp));
    });
});
```

My auth works, but I get the error:
```
"errors":[{"domain":"youtube.playlistItem","reason":"playlistItemsNotAccessible","message":"Forbidden"}]}
```

My guess is that jwt auth won't work for inserting items. Which seems strange to me. Is this accurate? Is there some other server-side way to insert items to a playlist? I don't need to upload videos.

Thanks a bunch.

**Comment by IonicaBizau** [comment]
> My guess is that jwt auth won't work for inserting items.

Yep. I remember that it did work in the past, but it doesn't seem to be supported now.

See #35 for more information. Also, you could check out [this blog post](http://ionicabizau.net/blog/26-uploading-videos-to-youtube-using-nodejs).

You're welcome! :sparkle:

**Comment by bradoyler** [comment]
@IonicaBizau Ok thanks. However, the JWT `.authorize` callback returns an `access_token` so couldn't that be used somehow to make the `playlistitem.insert` request?

**Comment by IonicaBizau** [comment]
No, because that access token doesn't have rights to access the YT resources. [Check this](https://developers.google.com/youtube/v3/guides/moving_to_oauth#service_accounts)–JWT is service account, from what I konw. :four_leaf_clover:

**Comment by bradoyler** [comment]
Oddly, Google actually states:
> Some examples of server-side scripts that use offline tokens: 
>  - A cron job that that updates playlists daily with new content

That's pretty awkward, but reinforces that your [auth example](https://github.com/IonicaBizau/youtube-api/blob/master/README.md#example) is really the only server-side way to write data to YT api.

Thanks.

**Comment by bradoyler** [comment]
I just realized your example requires browser input. Is there any way around this?

**Comment by bradoyler** [comment]
Ok, so it seems that I just need to get the proper `access_token` (via browser interaction once) and re-use that acess_token in my cron job.

**Comment by IonicaBizau** [comment]
> Ok, so it seems that I just need to get the proper access_token (via browser interaction once) and re-use that acess_token in my cron job.

Exactly–you only need to get it once, then it will be refreshed by the library I think.

See [this answer](https://github.com/google/google-api-nodejs-client/issues/379#issuecomment-76739274) to exactly the same problem.

**Comment by bradoyler** [comment]
Ok. I'm getting a `refresh_token` back but still can't find what I'm supposed do with it after the `access_token` expires (1 hr).

I'm happy to add this to your examples... once I get this figured out. :smile:

**Comment by IonicaBizau** [comment]
@bradoyler Just [set the credentials like here](https://github.com/IonicaBizau/youtube-api/blob/4e1167d538992e6f727b80f3c52b598ae2b53235/example/index.js#L57-L59)–the library will take care of the tokens. :smile_cat:

**Comment by bradoyler** [comment]
:+1: got it, thx.
