### ISSUE TITLE
Stream Comments

### ISSUE THREAD

**Issue by alantva** [IonicaBizau/youtube-api#43]
Hello,

Is there any API stream mode for comment as exists to Twitter?

**Comment by IonicaBizau** [comment]
I'm not sure... :cry: It seems the API supports such a thing: https://developers.google.com/youtube/v3/live/getting-started

If anyone has an example, please post it. :dizzy:

**Comment by Alexis01** [comment]
Hello,

I have a question about security.
When i send a video, having done a previous authentication, it would ensure avoid a man in the middle?

Thanks.

**Comment by IonicaBizau** [comment]
Hey @Alexis01! 

> When i send a video, having done a previous authentication, it would ensure avoid a man in the middle?

It depends on how you define *a man in the middle*. :thought_balloon: 
OAuth and APIs in general are made exactly for this reason: for allowing third-parties to access your account, by asking you first to accept that.

That's being said, the third-party is the *man in the middle*:

> `You` :arrow_right: `Third Party` (e.g. a Node.js command line app) :arrow_right: `YouTube API`

Basically, don't give access to these apps that you don't trust. :warning:

**Comment by Alexis01** [comment]
Ok,

Thanks @IonicaBizau .

**Comment by yoedy108** [comment]
@alantva Hi,
Do you mean share video to Twitter? or add a comment to a video? or stream live video?

**Comment by IonicaBizau** [comment]
@yoedy108 I think he means to get the live stream comments. Not sure, tho. :thought_balloon:

**Comment by yoedy108** [comment]
Yes, I wondered that myself as it wasn't very clear...
I know how to add comments to videos, but not how to get live stream comments, so I thought he might clear that up.

**Comment by alantva** [comment]
@yoedy108 No no. 
With twitter api, I receive a callback when I receive a new tweet. 
I was wondering if there is something on youtube api for comments?

(sorry for not writing this clear)

**Comment by alantva** [comment]
@IonicaBizau u are right.

**Comment by IonicaBizau** [comment]
@alantva I don't think you can do that with YouTube, but you can just check every 1 minute or so for new comments. :four_leaf_clover:

**Comment by IonicaBizau** [comment]
Moved here: https://github.com/google/google-api-nodejs-client/issues/574

**Comment by IonicaBizau** [comment]
https://github.com/google/google-api-nodejs-client/issues/574#issuecomment-374481800
