### ISSUE TITLE
Error: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

### ISSUE THREAD

**Issue by h3ku** [IonicaBizau/youtube-api#44]
Hi, when i try to make a request node drop this error.
The api key is correct and YoutubeDataApiV3 appear as active in the dev console.

<img width="638" alt="captura de pantalla 2015-10-28 a las 14 51 15" src="https://cloud.githubusercontent.com/assets/5603877/10790426/942345fc-7d83-11e5-9f37-f0e7c3582d42.png">
<img width="406" alt="captura de pantalla 2015-10-28 a las 14 50 33" src="https://cloud.githubusercontent.com/assets/5603877/10790427/944feb98-7d83-11e5-8a1c-d97c9622e0db.png">

**Comment by IonicaBizau** [comment]
Not sure, if this solves the problem, but it's obviously a problem:

In the `authenticate` function, replace `token` with `key`:

```js
youtube.authenticate({
    type: "key"
  , key: "APIKEY"
});
```

Hopefully this is the problem why you're getting this error. :dizzy:

**Comment by h3ku** [comment]
Oh thanks, this solve the problem.

**Comment by IonicaBizau** [comment]
Awesome! :grin:
