### ISSUE TITLE
Set a video thumbnail

### ISSUE THREAD

**Issue by hakima** [IonicaBizau/youtube-api#49]
Hello,
how can a video thumbnail?

I tried something like this:
<code>
Youtube.thumbnails.set({
                videoId: '******'
 });
</code>
Error: { [Error: null] code: 500 }

Thanks

**Comment by IonicaBizau** [comment]
> Error: { [Error: null] code: 500 }

That means the error is on their side (*Internal Server Error*).

According to the docs, make sure you have one of the scopes:

 - `https://www.googleapis.com/auth/youtubepartner`
 - `https://www.googleapis.com/auth/youtube.upload`
 - `https://www.googleapis.com/auth/youtube`
 - `https://www.googleapis.com/auth/youtube.force-ssl`

You definitely have to send to upload somehow the image. 

Try this:

```js
Youtube.thumbnails.set({
    resource: {
      videoId: '******'
    }
  , media: {
      body: Fs.createReadStream("video.mp4")
    }
}, ...);
```

The [API documentation](https://developers.google.com/youtube/v3/docs/thumbnails/set) could be useful. :memo:

**Comment by hakima** [comment]
Thank you, it's working :)

**Comment by IonicaBizau** [comment]
@hakima Oh, awesome! Honestly, didn't test the code, but happy to hear it's working. :smile:

**Comment by jasan-s** [comment]
does this mean I can only set a thumbnail after the uploaded video has a valid youtube id? Is it not possible to set a custom thumbnail at time of uploading video?

**Comment by XeraFiu-YTB** [comment]
> does this mean I can only set a thumbnail after the uploaded video has a valid youtube id? Is it not possible to set a custom thumbnail at time of uploading video? if how do i retrieve the videoid after upload?

Use the .then() method is a solution :
```js
Youtube.videos.insert({
        resource: {
            snippet: {
                title: "Testing YoutTube API NodeJS module",
                description: "Test video upload via YouTube API"
            }, 
            status: {
                privacyStatus: "private"
            }
        }, 
        part: "snippet,status",
        media: {
            body: fs.createReadStream("video.mkv")
        }
    }).then((data) => {
        console.log("Video sucessful uploaded !");
        console.log(data);
    })
```

**Comment by IonicaBizau** [comment]
You are right. If I am not wrong, there is no way to set the video thumbnail before the video would get processed.
