### ISSUE TITLE
Server side authentication

### ISSUE THREAD

**Issue by spassalacqua** [IonicaBizau/youtube-api#51]
Hello

First of all thank you for the great library.  I have some questions as I'm sort of a newbie.  I have an iOS app where I handle the google authentication (and get a token).  From my app I want to post the video to a server running node and then post the video to youtube without any further user interaction.  Is that possible, if so can you please tell me how because it's just not clear to me.

Thanks in advance!!

**Comment by IonicaBizau** [comment]
I don't think this is possible. In the past I remember that JWT authentication was working with YouTube API, but now, the workflow for this is to have a page where you will authenticate in the browser (using OAuth) and after the first authentication you will receive a refresh token. Use both: refresh and access tokens to [authenticate to YouTube API](https://github.com/IonicaBizau/youtube-api#oauth-refresh-token):

```js
Youtube.authenticate({
    type: "oauth"
  , refresh_token: "your refresh token"
  , client_id: "your client id"
  , client_secret: "your client secret"
  , redirect_url: "your refresh url"
});
```

That's being said, you will still have to make an initial authentication, but then it will run on the server without problems. Note the refresh token is received only in the first authentication.

**Comment by spassalacqua** [comment]
That's disappointing.  I thought for sure if I got a token from the iOS google sdk and passed it to the server side I would be good. It can be done with Facebook tokens

On Feb 7, 2016, at 11:47 PM, Ionică Bizău <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think this is possible. In the past I remember that JWT authentication was working with YouTube API, but now, the workflow for this is to have a page where you will authenticate in the browser (using OAuth) and after the first authentication you will receive a refresh token. Use both: refresh and access tokens to authenticate to YouTube API<https://github.com/IonicaBizau/youtube-api#oauth-refresh-token>:

Youtube.authenticate({
    type: "oauth"
  , refresh_token: "your refresh token"
  , client_id: "your client id"
  , client_secret: "your client secret"
  , redirect_url: "your refresh url"
});

That's being said, you will still have to make an initial authentication, but then it will run on the server without problems. Note the refresh token is received only in the first authentication.

**Comment by IonicaBizau** [comment]
@spassalacqua Make sure to ask this question on StackOverflow too. I'm not sure if there is really no other way. :books:
