### ISSUE TITLE
I can "this remix video" with this library?

### ISSUE THREAD

**Issue by armandomendivil** [IonicaBizau/youtube-api#52]
I need to spend a video of one channel to another, it's possible?

**Comment by IonicaBizau** [comment]
@armandomendivil Not sure what you mean—what is *this remix video*?

**Comment by armandomendivil** [comment]
Sorry is "remix this video", this option is for videos with license creative commons. 
"remix this video" it's used to transferring video from one YouTube account to another account

**Comment by IonicaBizau** [comment]
@armandomendivil I don't think that's possible via YouTube API, but you probably can do it using some kind of headless browser (Electron/Phantom).
