### ISSUE TITLE
Can this upload to a specific YT account?

### ISSUE THREAD

**Issue by lonelydatum** [IonicaBizau/youtube-api#62]
Hello,

I want to give users the ability to upload videos to my YT account. Most of the examples only upload to the user's YT account.

**Comment by IonicaBizau** [comment]
@lonelydatum Is that possible using the YouTube UI? If not, I think the answer is no... Unless you share with them your credentials.

**Comment by lonelydatum** [comment]
I don't think it is possible. Thanks for the confirmation. @IonicaBizau

**Comment by IonicaBizau** [comment]
@lonelydatum Then I guess we can close this issue. 💥
