### ISSUE TITLE
I got a error about lien

### ISSUE THREAD

**Issue by CM-moru** [IonicaBizau/youtube-api#63]
Hi
Thank you for good package

my app got google oatuth tokens and then
got a error message during request youtube api

> Trying to get the token using the following code: 4/BXsy-MapZST7Ll6d4OqiUq991Jhrxz8dtrUXWU2mNUU
> lien.lien(err, 400);
>                        ^
> 
> TypeError: lien.lien is not a function

do I have to close browser after get tokens?

**Comment by IonicaBizau** [comment]
It should be `lien.end` instead of `lien.lien`.
