### ISSUE TITLE
oauth2 Note

### ISSUE THREAD

**Issue by spikeon** [IonicaBizau/youtube-api#77]
I'm writing an api that takes videos uploaded to it and pushes them into our company youtube account.  

It'd be helpful if your documentation could show the users how to handle the oauth token if they are using the api in this manner, without user interaction.  Specifically that the developer has to open that url and then get the token and save it, and then refresh it every now and then to keep it active.

**Comment by IonicaBizau** [comment]
To be honest, I don't know. Probably it would be a good Stackoverflow question.
