### ISSUE TITLE
call request to youtube then Increase very big bandwidth

### ISSUE THREAD

**Issue by longnc2** [IonicaBizau/youtube-api#78]
Hi Team,

I have use youtube api in node js with request module, but every month Increase bandwidth very big to 100TB/month.
I have use gzip in request but same problem.
can help me suggest or any link to find and fix this problem for me.

Thanks,
Long Nguyen

**Comment by IonicaBizau** [comment]
Please ask the questions on Stackoverflow, providing sample code.
