### ISSUE TITLE
Vulnerable packages

### ISSUE THREAD

**Issue by binarious** [IonicaBizau/youtube-api#88]
Nsp detected packages with vulnerabilities:

- https://nodesecurity.io/advisories/658   
youtube-api@2.0.9 > googleapis@5.2.1 > gapitoken@0.1.5 > jws@3.0.0 > jwa@1.0.2 >  base64url@0.0.6      

- https://nodesecurity.io/advisories/664  
youtube-api@2.0.9 > googleapis@5.2.1 > request@2.72.0 > stringstream@0.0.6 

Any chance you can update `googleapis`? Current version is `30.0.0`.

**Comment by IonicaBizau** [comment]
Wow, 30. 😄 

Contributions are welcome! Currently I'm busy with other projects, but would like to merge a PR fixing this (I don't have time to bump and test the new version).
