### ISSUE TITLE
TypeScript?

### ISSUE THREAD

**Issue by TroyKomodo** [IonicaBizau/youtube-api#99]
Is there a d.ts?

**Comment by fxnoob** [comment]
it just adds auth in 'lib/index.js' This package uses https://github.com/googleapis/google-api-nodejs-client. which has types 
https://github.com/googleapis/google-api-nodejs-client#typescript. either define your types or use official package.

**Comment by denkan** [comment]
So basically, just use `@googleapis/youtube` instead of this lib, got it.

```ts
import { youtube_v3 } from '@googleapis/youtube';

async passiveAggressiveYoutubeSearch() {
  const youtube = new youtube_v3.Youtube({ auth: 'YOUR-API-KEY' });
  const searchResult = await youtube.search.list({ q: 'why wrap an already good lib into another?' });
  return searchRestult.data.items;
}
```

**Comment by commonpike** [comment]
>  q: 'why wrap an already good lib into another?' });


because @googleapis/youtube does not include the auth bit. 
and `googleapis` is way to big and takes minutes to compile.

but this seems to work:
```

import {OAuth2Client} from 'google-auth-library';
import { youtube_v3 } from '@googleapis/youtube';

...
const auth = new OAuth2Client();
auth.setCredentials({ access_token: "xxxxx" });
....
const service = new youtube_v3.Youtube({auth});

```
